### ISSUE TITLE
can't find package Tk

### ISSUE THREAD

**Issue by ghost** [utz82/pstk#1]
I think i am able to import pstk on Linux, but running (tk-start) throws:

#;10> (tk-start)
can't find package Tk

An error occurred inside Tcl/Tk
 wm protocol . WM_DELETE_WINDOW {callToScm g1}
 --> invalid command name "wm"

Again by evaluating (tk-start "tclsh8.4") (as i have chicken 5 in Emacs with the Geiser mode) i get the following error:

(tk-start "tclsh8.4")

=> Error: (string-append) "bad argument type - not a string": (#!eof)
Call history: 
<eval>   (geiser-eval (quote #f) (quote (tk-start "tclsh8.4")))
<eval>   (write-to-log form)
<eval>   (geiser-chicken-use-debug-log)
<eval>   (call-with-result thunk)
<eval>   ((call-with-current-continuation63 (##core#lambda (k61) (chicken.condition#with-exception-handler (##core#lambda (exn) (k61 (##core#lambda () (with-all-output-to-string (lambda () (write-exception exn)))))) (##core#lambda () (##sys#call-with-values (##core#lambda () (with-all-output-to-string (lambda () (call-with-values thunk (lambda v (set! result v)))))) (##core#lambda args62 (k61 (##core#lambda () (##sys#apply ##sys#values args62))))))))))
<eval>   (call-with-current-continuation63 (##core#lambda (k61) (chicken.condition#with-exception-handler (##core#lambda (exn) (k61 (##core#lambda () (with-all-output-to-string (lambda () (write-exception exn)))))) (##core#lambda () (##sys#call-with-values (##core#lambda () (with-all-output-to-string (lambda () (call-with-values thunk (lambda v (set! result v)))))) (##core#lambda args62 (k61 (##core#lambda () (##sys#apply ##sys#values args62)))))))))
<eval>   (chicken.condition#with-exception-handler (##core#lambda (exn) (k61 (##core#lambda () (with-all-output-to-string (lambda () (write-exception exn)))))) (##core#lambda () (##sys#call-with-values (##core#lambda () (with-all-output-to-string (lambda () (call-with-values thunk (lambda v (set! result v)))))) (##core#lambda args62 (k61 (##core#lambda () (##sys#apply ##sys#values args62)))))))
<eval>   (##sys#call-with-values (##core#lambda () (with-all-output-to-string (lambda () (call-with-values thunk (lambda v (set! result v)))))) (##core#lambda args62 (k61 (##core#lambda () (##sys#apply ##sys#values args62)))))
<eval>   (with-all-output-to-string (lambda () (call-with-values thunk (lambda v (set! result v)))))
<eval>   (with-output-to-string (lambda () (with-error-output-to-port (current-output-port) thunk)))
<eval>   (with-error-output-to-port (current-output-port) thunk)
<eval>   (current-output-port)
<eval>   (call-with-values thunk (lambda v (set! result v)))
<eval>   (eval form)
<syntax> (tk-start "tclsh8.4")
<eval>   (tk-start "tclsh8.4")

Error: (string-append) "bad argument type - not a string": (#!eof)
Call history: 
<eval>   (geiser-eval (quote #f) (quote (tk-start "tclsh8.4")))
<eval>   (write-to-log form)
<eval>   (geiser-chicken-use-debug-log)
<eval>   (call-with-result thunk)
<eval>   ((call-with-current-continuation63 (##core#lambda (k61) (chicken.condition#with-exception-handler (##core#lambda (exn) (k61 (##core#lambda () (with-all-output-to-string (lambda () (write-exception exn)))))) (##core#lambda () (##sys#call-with-values (##core#lambda () (with-all-output-to-string (lambda () (call-with-values thunk (lambda v (set! result v)))))) (##core#lambda args62 (k61 (##core#lambda () (##sys#apply ##sys#values args62))))))))))
<eval>   (call-with-current-continuation63 (##core#lambda (k61) (chicken.condition#with-exception-handler (##core#lambda (exn) (k61 (##core#lambda () (with-all-output-to-string (lambda () (write-exception exn)))))) (##core#lambda () (##sys#call-with-values (##core#lambda () (with-all-output-to-string (lambda () (call-with-values thunk (lambda v (set! result v)))))) (##core#lambda args62 (k61 (##core#lambda () (##sys#apply ##sys#values args62)))))))))
<eval>   (chicken.condition#with-exception-handler (##core#lambda (exn) (k61 (##core#lambda () (with-all-output-to-string (lambda () (write-exception exn)))))) (##core#lambda () (##sys#call-with-values (##core#lambda () (with-all-output-to-string (lambda () (call-with-values thunk (lambda v (set! result v)))))) (##core#lambda args62 (k61 (##core#lambda () (##sys#apply ##sys#values args62)))))))
<eval>   (##sys#call-with-values (##core#lambda () (with-all-output-to-string (lambda () (call-with-values thunk (lambda v (set! result v)))))) (##core#lambda args62 (k61 (##core#lambda () (##sys#apply ##sys#values args62)))))
<eval>   (with-all-output-to-string (lambda () (call-with-values thunk (lambda v (set! result v)))))
<eval>   (with-output-to-string (lambda () (with-error-output-to-port (current-output-port) thunk)))
<eval>   (with-error-output-to-port (current-output-port) thunk)
<eval>   (current-output-port)
<eval>   (call-with-values thunk (lambda v (set! result v)))
<eval>   (eval form)
<syntax> (tk-start "tclsh8.4")
<eval>   (tk-start "tclsh8.4")

**Comment by utz82** [comment]
Unfortunately I cannot reproduce the issue.
Which Linux distribution are you using? Does Tk work by itself (ie when invoked through tclsh)?
Also, would upgrading tclsh be an option for you? I did not test with 8.4 myself, though I don't see why it should be broken either since pretty much all code changes since the 8.4 days were related to CHICKEN compatibility.

**Comment by ghost** [comment]
I am using MX Linux (which is a Debian). I can start tclsh8.6 in terminal, i dont know how to invoke tk.
Is Tk implemented completely in PSTK, or is it only bindings for parts of it. Now i am using Racket which comes with an awsome infrastructure including built in GUI library, however i dont really like the Language. I Like more Chicken but i cant find such a comprehensive and good documented GUI module for it. :-(

**Comment by utz82** [comment]
PSTk talks to an existing Tk installation via a pipe. It does not provide its own Tk implementation.

On most Debian-based distros, Tk should be installed by default. However, maybe that's not the case for MX Linux? Try `apt-get install tk`.

Note that while PSTk documentation is quite extensive (clone the repo for easy access to the docs), it isn't always 100% up to date. You also need at least a basic understanding of Tk to use it.

If you find that PSTk isn't your thing, you could also try the [iup](https://wiki.call-cc.org/eggref/5/iup) egg, which is very well documented, and the iup gui library itself is extensive.

**Comment by ghost** [comment]
Strangely i didn't have the tk package! Installing it now runs the programm. However running your example hello.scm upon evaluating (tk-event-loop) i don't get anything from clicking the button, it kind of freezes!
And if i am in Emacs the whole Emacs becomes frozen and not communicating anymore. Do you have any idea why this could happen? 

Update:

In fact entering the tk-event-loop shifts the whole functionality to the frame. I get the whole (display "Hello Worlds") first after i close the frame. Is there a possibility to keep the interpreter (csi) or Emacs still active and addresseable while event-loop running?

**Comment by utz82** [comment]
That's correct, calling tk-event-loop essentially hands over control to Tk. Afaik the only way around this is to use some sort of task switching/multitasking.

Also yes, geiser/emacs is not very good at this. I prefer plain csi when trying out pstk things.
