### ISSUE TITLE
Widget Properties

### ISSUE THREAD

**Issue by ghost** [utz82/pstk#2]
Is there any way of getting properties of widget for resetting these? For example changing the text of a button after packing it? Also is there a way of tracking created widgets? a table where things are being saved?

**Comment by utz82** [comment]
The idea is that you do the tracking yourself, ie. by naming individual widgets with `define` or holding them in a list/struct/whatever you like.

To inspect widget properties, just run a `'cget` query on a widget as you would in Tcl/Tk.

**Comment by ghost** [comment]
Thanks for your answer! Sould configuring a widget also work as in Tk? I was trying this:

(define b1 (tk 'create-widget 'button
	       #:text "Hello button"
	       #:command (lambda () 3.14)
	       #:padx 20 #:pady 20))

(tk/pack b1)
(b1 'config #:text "Hi")

But this doesn't change the -text.

**Comment by utz82** [comment]
That should be

(b1 'configure #:text "Hi")

**Comment by ghost** [comment]
Thanks!
